# Generated by Django 5.1.1 on 2024-12-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify_Wrapped', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wrap',
            name='top_suggested_songs',
        ),
        migrations.AlterField(
            model_name='wrap',
            name='spirit_animal',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
