# Generated by Django 5.1.2 on 2024-11-06 20:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify_Wrapped', '0002_wrap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wrap',
            name='id',
        ),
        migrations.AddField(
            model_name='wrap',
            name='theme',
            field=models.CharField(default='dark', max_length=50),
        ),
        migrations.AddField(
            model_name='wrap',
            name='time_range',
            field=models.CharField(choices=[('short_term', 'Last 4 Weeks'), ('medium_term', 'Last 6 Months'), ('long_term', 'All Time')], default='medium_term', max_length=20),
        ),
        migrations.AddField(
            model_name='wrap',
            name='title',
            field=models.CharField(default='Untitled Wrap', max_length=255),
        ),
        migrations.AddField(
            model_name='wrap',
            name='wrap_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
