# Generated by Django 5.1.2 on 2024-11-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify_Wrapped', '0003_remove_wrap_id_wrap_theme_wrap_time_range_wrap_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrap',
            name='top_genres',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
