# Generated by Django 5.1.2 on 2024-11-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify_Wrapped', '0004_wrap_top_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrap',
            name='top_album',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
