# Generated by Django 5.1.3 on 2024-11-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify_Wrapped', '0005_wrap_top_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrap',
            name='top_playlists',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wrap',
            name='top_suggested_songs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
