# Generated by Django 5.1.3 on 2024-11-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify_Wrapped', '0006_wrap_top_playlists_wrap_top_suggested_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrap',
            name='is_publix',
            field=models.BooleanField(default=False),
        ),
    ]
