# Generated by Django 5.1.3 on 2024-11-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify_Wrapped', '0007_wrap_is_publix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wrap',
            name='is_publix',
        ),
        migrations.AddField(
            model_name='wrap',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
