# Generated by Django 5.1.3 on 2024-11-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify_Wrapped', '0008_remove_wrap_is_publix_wrap_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrap',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
