# Generated by Django 5.1.3 on 2024-11-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify_Wrapped', '0009_alter_wrap_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by_users', to='Spotify_Wrapped.wrap'),
        ),
    ]
