# Generated by Django 5.1.3 on 2024-11-29 04:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify_Wrapped', '0011_wrap_spirit_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrap',
            name='liked_by_users',
            field=models.ManyToManyField(blank=True, related_name='liked_wraps', to=settings.AUTH_USER_MODEL),
        ),
    ]
